### PR TITLE
extension/windowmatch: GNOME 48 compatibility

### LINKED ISSUE #1188: Support for Gnome 48
### GNOME Shell version

GNOME Shell 48.beta

### Linux distro

"Debian GNU/Linux trixie/sid"

### ddterm version

ddterm does not start:
TypeError: (intermediate value).get_window_actors is not a function

### Session type

X11

### Special configuration

- [ ] High DPI
- [x] More than one monitor

### All installed extensions

```Text
lockkeys@vaina.lt
  Name: Lock Keys
  Description: Numlock & Capslock status on the panel.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/lockkeys@vaina.lt
  URL: https://github.com/kazysmaster/gnome-shell-extension-lockkeys
  Version: 60
  Enabled: Yes
  State: ACTIVE

quick-settings-tweaks@qwreey
  Name: [QSTweak] Quick Setting Tweaker
  Description: Let's tweak gnome 43's quick settings! You can add Media Controls, Notifications, Volume Mixer on quick settings and remove useless buttons!
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey
  URL: https://github.com/qwreey75/quick-settings-tweaks
  Version: 27
  Enabled: Yes
  State: ACTIVE

batterytime@typeof.pw
  Name: Battery time
  Description: Show battery estimated remaining time
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/batterytime@typeof.pw
  URL: https://github.com/pomoke/battery_time
  Version: 7
  Enabled: Yes
  State: ACTIVE

wiggle@mechtifs
  Name: Wiggle
  Description: Wiggle is a GNOME Shell extension that magnifies the cursor when the mouse is moved rapidly.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/wiggle@mechtifs
  URL: https://github.com/mechtifs/wiggle
  Version: 5
  Enabled: Yes
  State: ERROR

Bluetooth-Battery-Meter@maniacx.github.com
  Name: Bluetooth Battery Meter
  Description: A Gnome extension featuring indicator icons in system tray, serving as meter for Bluetooth device battery levels and providing detailed battery levels via icon/text in the Bluetooth quick settings menu.

Note:
Certain Bluetooth devices do not report battery level until Bluez's experimental features are enabled in system. Check Readme for details.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/Bluetooth-Battery-Meter@maniacx.github.com
  URL: https://github.com/maniacx/Bluetooth-Battery-Meter
  Version: 28
  Enabled: Yes
  State: ACTIVE

trayIconsReloaded@selfmade.pl
  Name: Tray Icons: Reloaded
  Description: Tray Icons Reloaded is a GNOME Shell extension which bring back Tray Icons to top panel, with additional features.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/trayIconsReloaded@selfmade.pl
  URL: https://github.com/MartinPL/Tray-Icons-Reloaded
  Version: 31
  Enabled: Yes
  State: ACTIVE

smartlock@huy.im
  Name: Bluetooth Smart Lock
  Description: Dynamic lock for GNOME. Use your smart phone/watch/band to lock your desktop automatically when you step away.

When your device is out of bluetooth range or get disconnected, it will lock your desktop automatically.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/smartlock@huy.im
  URL: https://github.com/ba0f3/gnome-bluetooth-smartlock
  Version: 15
  Enabled: No
  State: INITIALIZED

eye-on-cursor@djinnalexio.github.io
  Name: Eye on Cursor
  Description: Let your desktop "keep an eye" on your mouse! And with the included cursor indicator, keep track of your pointer's every action!

Try Eye on Cursor, a fun and practical extension that gives your panel eyes that constantly follow your mouse. This quirky feature, combined with a highly customizable mouse tracker that highlights clicks, makes it easier than ever to monitor your mouse movements, ensuring your pointer gets all the attention it needs.

This extension is the latest version of 'Eye and Mouse Extended' by Alexey Lovchikov.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/eye-on-cursor@djinnalexio.github.io
  URL: https://github.com/djinnalexio/eye-on-cursor/
  Version: 1.3.1 (8)
  Enabled: No
  State: INITIALIZED

status-area-horizontal-spacing@mathematical.coffee.gmail.com
  Name: Status Area Horizontal Spacing
  Description: Reduce the horizontal spacing between icons in the top-right status area
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/status-area-horizontal-spacing@mathematical.coffee.gmail.com
  URL: https://gitlab.com/p91paul/status-area-horizontal-spacing-gnome-shell-extension
  Version: 29
  Enabled: Yes
  State: ACTIVE

ddterm@amezin.github.com
  Name: ddterm
  Description: Another drop down terminal extension for GNOME Shell. With tabs. Works on Wayland natively
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com
  URL: https://github.com/ddterm/gnome-shell-extension-ddterm
  Version: 56
  Enabled: Yes
  State: ERROR

color-picker@tuberry
  Name: Color Picker
  Description: Simple color picker for GNOME Shell

For support, please report any issues via the homepage link below.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/color-picker@tuberry
  URL: https://github.com/tuberry/color-picker
  Version: 45
  Enabled: Yes
  State: ACTIVE

extension-list@tu.berry
  Name: Extension List
  Description: Simple GNOME Shell extension manager in the top panel

For support, please report any issues via the homepage link below.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/extension-list@tu.berry
  URL: https://github.com/tuberry/extension-list
  Version: 41
  Enabled: No
  State: INITIALIZED

luminus-shell@dikasp.gitlab
  Name: Luminus Shell
  Description: An alternative light theme integration (shell only).
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/luminus-shell@dikasp.gitlab
  URL: https://gitlab.com/dikasetyaprayogi/luminus-project
  Version: 47.v4 (17)
  Enabled: No
  State: INITIALIZED

gradienttopbar@pshow.org
  Name: Gradient Top Bar
  Description: Makes GNOME's panel's background gradient. You can edit the colour scheme from the extension's settings in Gnome 45+.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/gradienttopbar@pshow.org
  URL: https://github.com/petar-v/gradienttopbar
  Version: 20
  Enabled: Yes
  State: ACTIVE

battery-indicator-icon@Deminder
  Name: Battery Indicator Icon
  Description: Replace the battery indicator icon with a circle or portrait.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/battery-indicator-icon@Deminder
  URL: https://github.com/Deminder/battery-indicator-icon
  Version: 15
  Enabled: Yes
  State: ACTIVE

TouchpadOnOff@romano.rgtti.com
  Name: Touchpad On Off
  Description: Toggle touchpad on or off
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/TouchpadOnOff@romano.rgtti.com
  URL: https://github.com/Rmano/gse-touchpad-onoff
  Version: 5
  Enabled: Yes
  State: ACTIVE

weatheroclock@CleoMenezesJr.github.io
  Name: Weather O'Clock
  Description: Display the current weather inside the pill next to the clock. GNOME Weather is required for this extension to work.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/weatheroclock@CleoMenezesJr.github.io
  URL: https://github.com/CleoMenezesJr/weather-oclock
  Original author: JasonLG1979@github.io
  Version: 47.0 (14)
  Enabled: Yes
  State: ACTIVE

freon@UshakovVasilii_Github.yahoo.com
  Name: Freon
  Description: Shows CPU temperature, disk temperature, video card temperature (NVIDIA/Catalyst/Bumblebee&NVIDIA), voltage and fan RPM (forked from xtranophilist/gnome-shell-extension-sensors)
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/freon@UshakovVasilii_Github.yahoo.com
  URL: https://github.com/UshakovVasilii/gnome-shell-extension-freon
  Version: 57
  Enabled: Yes
  State: ACTIVE

tuxedo-fnlock-status@stevenseifried.github.io
  Name: TUXEDO FnLock status
  Description: Show the FnLock status of TUXEDO devices. This extension is not affiliated, funded, or in any way associated with TUXEDO. This extension is a fork of the 'FnLock switch (ThinkPad Compact USB Keyboard)' extension. tuxedo-drivers v4.0.0 or newer must be installed.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/tuxedo-fnlock-status@stevenseifried.github.io
  URL: https://github.com/StevenSeifried/tuxedo-fnlock-status
  Version: 3
  Enabled: Yes
  State: ACTIVE

dim-completed-calendar-events@marcinjahn.com
  Name: Dim Completed Calendar Events
  Description: Dim completed events in the top panel menu to easily distinguish between upcoming and past events. You can also highlight events that are ongoing.
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/dim-completed-calendar-events@marcinjahn.com
  URL: https://github.com/marcinjahn/gnome-dim-completed-calendar-events-extension
  Version: 8
  Enabled: Yes
  State: ACTIVE

calc@danigm.wadobo.com
  Name: calc
  Description: Simple run dialog calculation
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/calc@danigm.wadobo.com
  URL: https://github.com/danigm/gnome-shell-calculator
  Version: 16
  Enabled: Yes
  State: ACTIVE

BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm
  Name: Bring Out Submenu Of Power Off Button
  Description: Bring Out Submenu Of Power Off Button
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/BringOutSubmenuOfPowerOffLogoutButton@pratap.fastmail.fm
  URL: https://github.com/PRATAP-KUMAR/bring-out-submenu-of-power-off-logout
  Version: 60
  Enabled: Yes
  State: ACTIVE

simplebreakreminder@castillodel.com
  Name: Simple Break Reminder
  Description: It's important to remember to take a break
  Path: /srv/home/michael/.local/share/gnome-shell/extensions/simplebreakreminder@castillodel.com
  URL: https://github.com/CastilloDel/simplebreakreminder
  Version: 9
  Enabled: No
  State: INITIALIZED

bluetooth-quick-connect@bjarosze.gmail.com
  Name: Bluetooth Quick Connect
  Description: This extension allows paired Bluetooth devices to be connected and disconnected via the GNOME system menu, Shows battery status and more.

  Path: /srv/home/michael/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com
  URL: https://github.com/Extensions-Valhalla/gnome-bluetooth-quick-connect
  Version: 52
  Enabled: Yes
  State: ACTIVE

apps-menu@gnome-shell-extensions.gcampax.github.com
  Name: Apps Menu
  Description: Add a category-based menu for apps.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/apps-menu@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

places-menu@gnome-shell-extensions.gcampax.github.com
  Name: Places Status Indicator
  Description: Add a menu for quickly navigating places in the system.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/places-menu@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

launch-new-instance@gnome-shell-extensions.gcampax.github.com
  Name: Launch new instance
  Description: Always launch a new instance when clicking in the dash or the application view.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/launch-new-instance@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

window-list@gnome-shell-extensions.gcampax.github.com
  Name: Window List
  Description: Display a window list at the bottom of the screen.
This extension is part of Classic Mode and is officially supported by GNOME. Please do not report bugs using the form below, use GNOME's GitLab instance instead.
  Path: /usr/share/gnome-shell/extensions/window-list@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

auto-move-windows@gnome-shell-extensions.gcampax.github.com
  Name: Auto Move Windows
  Description: Move applications to specific workspaces when they create windows.
  Path: /usr/share/gnome-shell/extensions/auto-move-windows@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

drive-menu@gnome-shell-extensions.gcampax.github.com
  Name: Removable Drive Menu
  Description: A status menu for accessing and unmounting removable devices.
  Path: /usr/share/gnome-shell/extensions/drive-menu@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

light-style@gnome-shell-extensions.gcampax.github.com
  Name: Light Style
  Description: Switch default to light style
  Path: /usr/share/gnome-shell/extensions/light-style@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: Yes
  State: ACTIVE

native-window-placement@gnome-shell-extensions.gcampax.github.com
  Name: Native Window Placement
  Description: Arrange windows in overview in a more compact way.
  Path: /usr/share/gnome-shell/extensions/native-window-placement@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
  Name: Screenshot Window Sizer
  Description: Resize windows for GNOME Software screenshots with Ctrl+Alt+s shortcut
  Path: /usr/share/gnome-shell/extensions/screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

system-monitor@gnome-shell-extensions.gcampax.github.com
  Name: System Monitor
  Description: Monitor system from the top bar
  Path: /usr/share/gnome-shell/extensions/system-monitor@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

user-theme@gnome-shell-extensions.gcampax.github.com
  Name: User Themes
  Description: Load shell themes from user directory.
  Path: /usr/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED

windowsNavigator@gnome-shell-extensions.gcampax.github.com
  Name: windowNavigator
  Description: Allow keyboard selection of windows and workspaces in overlay mode. <Ctrl>number selects a workspace, and <Alt>number selects a window.
  Path: /usr/share/gnome-shell/extensions/windowsNavigator@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Original author: zaspire@rambler.ru
  Enabled: No
  State: INITIALIZED

workspace-indicator@gnome-shell-extensions.gcampax.github.com
  Name: Workspace Indicator
  Description: Put an indicator on the panel signaling in which workspace you are, and give you the possibility of switching to another one.
  Path: /usr/share/gnome-shell/extensions/workspace-indicator@gnome-shell-extensions.gcampax.github.com
  URL: https://gitlab.gnome.org/GNOME/gnome-shell-extensions
  Enabled: No
  State: INITIALIZED
```

### ddterm settings dump

```ini
dconf dump /com/github/amezin/ddterm/
[/]
background-color='rgb(0x17, 0x14, 0x21)'
foreground-color='rgb(0xd0, 0xcf, 0xcc)'
panel-icon-type='none'
use-theme-colors=false
window-maximize=false
window-size=0.55092592592592593
window-skip-taskbar=true
```

### Description

```
gnome-shell[3205]: Extension ddterm@amezin.github.com: TypeError: (intermediate value).get_window_actors is not a function
                                         
                                         Stack trace:
                                           _init@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/windowmatch.js:46:14
                                           _init@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/windowmatch.js:116:15
                                           DDTermWindowMatchGeneric@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/windowmatch.js:31:4
                                           DDTermWindowMatch@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/windowmatch.js:112:4
                                           create_window_matcher@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/extension.js:31:28
                                           _enable@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/extension.js:338:31
                                           EnabledExtension@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/extension.js:229:18
                                           enable@file:///srv/home/michael/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/ddterm/shell/extension.js:529:30
                                           _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
                                           loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:433:32
                                           async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:741:24
                                           async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:747:48
                                           _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:782:20
                                           async*init@resource:///org/gnome/shell/ui/extensionSystem.js:76:14
                                           _initializeUI@resource:///org/gnome/shell/ui/main.js:329:22
                                           start@resource:///org/gnome/shell/ui/main.js:180:11
                                           @resource:///org/gnome/shell/ui/init.js:12:47
                                           @resource:///org/gnome/shell/ui/init.js:21:20
```

[journal.txt](https://github.com/user-attachments/files/18683900/journal.txt)

### PR DESCRIPTION
**Pull request by mokilcde**
Closes #1188

### CODE REVIEW

**Comment by amezin** [comment]
Could you make it compatible with old GNOME versions too? https://gjs.guide/extensions/development/targeting-older-gnome.html#adapting-to-different-code

**Review by mokilcde — COMMENTED** [review]
Better?

**Comment by amezin** [comment]
> Better?

As you can see, tests are passing now.

But also you've probably noticed that I avoid version number checks when possible. Here you can simply check whether the method exists: https://gjs.guide/extensions/development/targeting-older-gnome.html#feature-detection, and the code will be shorter. Also, there's no need to write `.forEach()` twice.

File: ddterm/shell/windowmatch.js [hunk 1]
```diff
@@ -43,9 +46,15 @@ export const WindowMatchGeneric = GObject.registerClass({
             }
         });
 
-        Meta.get_window_actors(this.display).forEach(actor => {
-            this._watch_window(actor.meta_window);
-        });
+        if (shellVersion < 48) {
```
Comment (amezin) [inline ddterm/shell/windowmatch.js:49]: Please check if method exists instead of doing version check. It'll be both shorter and simpler.

File: ddterm/shell/windowmatch.js [hunk 2]
```diff
@@ -43,9 +46,15 @@ export const WindowMatchGeneric = GObject.registerClass({
...
+            Meta.get_window_actors(this.display).forEach(actor => {
+                this._watch_window(actor.meta_window);
+            });
+        } else {
+            global.compositor.get_window_actors(this.display).forEach(actor => {
+                this._watch_window(actor.meta_window);
+            });
```
Comment (amezin) [inline ddterm/shell/windowmatch.js:56]: There's no need to have two copies of the same `forEach()`. You could store the return value of the correct `.get_window_actors()` in a variable, and then call `.forEach()` on it - only once, outside of `if`.

**Review by amezin — CHANGES_REQUESTED** [review]

**Comment by mokilcde** [comment]
Check it again

**Review by amezin — CHANGES_REQUESTED** [review]
Why did you do https://github.com/ddterm/gnome-shell-extension-ddterm/pull/1196/commits/6477ad9f5df8eb1770d5de4659605f0ae8d97707 ? https://github.com/ddterm/gnome-shell-extension-ddterm/pull/1196/commits/badddb02248979e79a630f88c4a04fcefeee9db1 was almost correct - except `global.compositor` is not even defined on really old GNOME versions. `global.compositor?.get_window_actors` should work.

**Comment by mokilcde** [comment]
It crashed on Debian 12 (stable) and Ubuntu 22.04. Check [here)(https://github.com/ddterm/gnome-shell-extension-ddterm/pull/1196/commits/badddb02248979e79a630f88c4a04fcefeee9db1)

You can change it and test it

**Comment by amezin** [comment]
> It crashed on Debian 12 (stable) and Ubuntu 22.04

Yes, that's exactly what I mean by "global.compositor is not defined on really old GNOME versions". If you change `if (global.compositor.get_window_actors)` to `if (global.compositor?.get_window_actors)` it will work on all GNOME versions.

Also, it would be a bit nicer with `const` and ternary operator, but this is optional.

**Review by amezin — APPROVED** [review]
